// content.js — UA + PL copy for the Natalia Rudnik landing page.
// All strings live here; app.js swaps languages by re-reading window.CONTENT.

window.CONTENT = {
  uk: {
    seo: {
      title: "Наталія Руднік — Рейки, авторські курси та медитації",
      description: "Наталія Руднік — провідник Рейки, автор трансформаційних проектів. Сеанси Рейки, розстановки, авторські курси та медитації для глибокої взаємодії із собою.",
      ogLocale: "uk_UA",
    },
    nav: {
      home: "Головна", about: "Про мене", services: "Послуги", courses: "Курси",
      meditations: "Медитації", reviews: "Відгуки", contacts: "Контакти", book: "Записатись",
    },
    hero: {
      positioning: "автор трансформаційних проектів · провідник Рейки",
      h1: "Наталія Руднік",
      sub: "Створюю глибоку взаємодію із собою через Рейки, авторські курси, медитації та розстановки.",
      ctaBook: "Записатись",
      ctaCourses: "Курси",
      meta: ["онлайн і офлайн", "індивідуальний підхід", "перша консультація — безкоштовно"],
      portraitLabel: "Наталія Руднік",
    },
    about: {
      kicker: "01 · про мене",
      title: "Коротко про мене",
      intro: "Я працюю з енергією, тілом і свідомістю — щоб ви відчули опору в собі. За цими цифрами — практика, навчання та реальні зміни клієнтів.",
      stats: [
        { value: "3", label: "роки практики" },
        { value: "700+", label: "годин медитацій" },
        { value: "23 000$", label: "інвестицій у навчання" },
        { value: "5", label: "успішних кейсів" },
      ],
      certsLabel: "сертифікати та навчання",
      certs: [
        "Рейки — 1 ступінь",
        "Рейки — 2 ступінь",
        "Масажні практики",
        "Тетахілінг, Регрес та китайська метафізика",
      ],
      cta: "Детальніше",
      portraitLabel: "Наталія Руднік",
    },
    services: {
      kicker: "02 · послуги",
      title: "Формати роботи зі мною",
      sub: "Оберіть те, що відгукується саме сьогодні — від знайомства до глибокої трансформації.",
      items: [
        {
          tag: "знайомство", glyph: "☾",
          name: "Безкоштовна консультація",
          desc: "20–30 хвилин розмови, щоб зрозуміти ваш запит і підібрати формат роботи. Без зобов'язань.",
          price: "безкоштовно", cta: "Записатись",
        },
        {
          tag: "сеанс", glyph: "✦",
          name: "Класичний сеанс Рейки",
          desc: "Робота з енергією для відновлення, спокою та зняття напруги. Очно або дистанційно.",
          price: "від 000 ₴", cta: "Записатись",
        },
        {
          tag: "глибша робота", glyph: "❋",
          name: "Сесія «Запит — Рішення»",
          desc: "Індивідуальна сесія, де ми разом розбираємо конкретний запит і знаходимо рішення.",
          price: "від 000 ₴", cta: "Записатись", featured: true,
        },
        {
          tag: "розстановка", glyph: "✶",
          name: "Розстановка",
          desc: "Метод, що допомагає побачити приховані причини ситуації та відновити внутрішній баланс.",
          price: "від 000 ₴", cta: "Записатись",
        },
      ],
    },
    courses: {
      kicker: "03 · курси",
      title: "Авторські курси",
      sub: "Глибокі програми для системної роботи над собою у власному темпі.",
      items: [
        {
          tag: "курс", name: "Жіноча сила",
          desc: "Курс про повернення до себе, відновлення енергії та внутрішньої опори. Практики, медитації та супровід.",
          price: "від 000 ₴", cta: "Дізнатися більше",
        },
        {
          tag: "курс", name: "Сценарій",
          desc: "Робота з життєвим сценарієм: побачити повторювані патерни та переписати їх на свій лад.",
          price: "від 000 ₴", cta: "Дізнатися більше",
        },
      ],
    },
    mini: {
      kicker: "04 · мініпродукти",
      title: "Мініпродукти для самостійної роботи",
      sub: "Невеликі практичні матеріали — щоб почати працювати із собою вже сьогодні.",
      priceLabel: "000 ₴",
      items: [
        { name: "Цілі. Маніфест. Бажання.", desc: "Як ставити цілі, що здійснюються, і повертати собі право бажати." },
        { name: "Фен-шуй базовий для початківців", desc: "Прості принципи простору, що підтримує вас і вашу енергію." },
        { name: "Призначення та Місія", desc: "Практика для пошуку власного напряму та сенсу." },
        { name: "Тіньова сторона та субособистості", desc: "Знайомство зі своїми тіньовими частинами — без страху та осуду." },
        { name: "Багатство. Гроші. Реалізація.", desc: "Робота з грошовими переконаннями та дозволом на достаток." },
      ],
    },
    meditations: {
      kicker: "05 · медитації",
      title: "Пакет медитацій",
      sub: "Авторські медитації, які повертають у контакт із тілом та спокоєм. Слухайте у зручний час, у власному темпі.",
      features: ["медитації у записі", "доступ після оплати — назавжди", "онлайн формат"],
      cta: "Отримати доступ",
    },
    reviews: {
      kicker: "06 · відгуки та кейси",
      title: "Історії трансформацій",
      sub: "Реальні запити та результати клієнтів. Імена — зі згоди.",
      requestLabel: "Запит",
      resultLabel: "Результат",
      items: [
        {
          name: "Олена", role: "33 роки",
          request: "Постійна тривога та відчуття, що живе не своє життя.",
          result: "Через місяць роботи повернулися ясність і спокій. Наважилася на зміну роботи.",
        },
        {
          name: "Ірина", role: "41 рік",
          request: "Втома, яка не минала навіть після відпочинку.",
          result: "Відновила енергію, навчилася відчувати свої межі та казати «ні».",
        },
        {
          name: "Марія", role: "29 років",
          request: "Не розуміла свого напряму та призначення.",
          result: "Знайшла опору в собі й чіткіше побачила, куди рухатися далі.",
        },
      ],
      cta: "Більше відгуків",
    },
    faq: {
      kicker: "07 · питання",
      title: "Найчастіші питання",
      items: [
        { q: "Як проходить сесія?", a: "Ми зустрічаємось онлайн або очно. Спочатку коротко проговорюємо ваш запит, далі — сама практика. Після сеансу я ділюся спостереженнями та рекомендаціями." },
        { q: "Чи це безпечно?", a: "Так. Рейки — м'який метод, що не має протипоказань. Він не замінює медичну допомогу, а доповнює турботу про себе." },
        { q: "Скільки триває робота?", a: "Залежить від запиту. Іноді достатньо одного сеансу, для глибших змін — серія зустрічей або курс. Формат підбираємо разом." },
        { q: "Що таке Рейки?", a: "Це практика роботи з енергією для відновлення балансу, спокою та ресурсу. Працює м'яко — через дотик або дистанційно." },
        { q: "Як обрати формат?", a: "Найпростіше — почати з безкоштовної консультації. За 20–30 хвилин я зрозумію ваш запит і підкажу, що підійде саме вам." },
        { q: "Чи це суперечить моїй релігії?", a: "Ні. Рейки — це не релігія і не вимагає віри. Це практика турботи про себе, яка поєднується з будь-яким світоглядом." },
      ],
    },
    contacts: {
      kicker: "08 · контакти",
      title: "Зробимо перший крок",
      sub: "Напишіть мені у будь-який зручний спосіб або залиште заявку — я відповім особисто.",
      channels: [
        { kind: "Instagram", value: "@nataliarudnik", href: "#" },
        { kind: "TikTok", value: "@nataliarudnik", href: "#" },
        { kind: "Telegram", value: "@nataliarudnik", href: "#" },
        { kind: "Email", value: "hello@nataliarudnik.com", href: "mailto:hello@nataliarudnik.com" },
        { kind: "WhatsApp", value: "+380 00 000 00 00", href: "#" },
      ],
      orWrite: "або залиште заявку:",
      formName: "ваше ім'я",
      formContact: "email або телефон",
      formCta: "Надіслати заявку",
      footnote: "відповідаю особисто, зазвичай протягом дня",
    },
    footer: {
      tagline: "повертайтеся до себе — глибоко та по-справжньому",
      copyright: "© 2026 Наталія Руднік",
      links: ["Політика конфіденційності", "Публічна оферта"],
    },
  },

  pl: {
    seo: {
      title: "Natalia Rudnik — Reiki, autorskie kursy i medytacje",
      description: "Natalia Rudnik — przewodniczka Reiki, autorka projektów transformacyjnych. Sesje Reiki, ustawienia, autorskie kursy i medytacje dla głębokiego kontaktu ze sobą.",
      ogLocale: "pl_PL",
    },
    nav: {
      home: "Strona główna", about: "O mnie", services: "Usługi", courses: "Kursy",
      meditations: "Medytacje", reviews: "Opinie", contacts: "Kontakt", book: "Umów się",
    },
    hero: {
      positioning: "autorka projektów transformacyjnych · przewodniczka Reiki",
      h1: "Natalia Rudnik",
      sub: "Tworzę głęboki kontakt ze sobą poprzez Reiki, autorskie kursy, medytacje i ustawienia.",
      ctaBook: "Umów się",
      ctaCourses: "Kursy",
      meta: ["online i stacjonarnie", "indywidualne podejście", "pierwsza konsultacja — bezpłatnie"],
      portraitLabel: "Natalia Rudnik",
    },
    about: {
      kicker: "01 · o mnie",
      title: "Krótko o mnie",
      intro: "Pracuję z energią, ciałem i świadomością — by dać ci oparcie w sobie. Za tymi liczbami stoi praktyka, nauka i realne zmiany u klientek.",
      stats: [
        { value: "3", label: "lata praktyki" },
        { value: "700+", label: "godzin medytacji" },
        { value: "23 000$", label: "zainwestowane w naukę" },
        { value: "5", label: "udanych historii" },
      ],
      certsLabel: "certyfikaty i szkolenia",
      certs: [
        "Reiki — I stopień",
        "Reiki — II stopień",
        "Praktyki masażu",
        "ThetaHealing, Regresja oraz chińska metafizyka",
      ],
      cta: "Więcej",
      portraitLabel: "Natalia Rudnik",
    },
    services: {
      kicker: "02 · usługi",
      title: "Formaty pracy ze mną",
      sub: "Wybierz to, co rezonuje właśnie dziś — od poznania się po głęboką transformację.",
      items: [
        {
          tag: "poznanie", glyph: "☾",
          name: "Bezpłatna konsultacja",
          desc: "20–30 minut rozmowy, by zrozumieć twoją potrzebę i dobrać format pracy. Bez zobowiązań.",
          price: "bezpłatnie", cta: "Umów się",
        },
        {
          tag: "sesja", glyph: "✦",
          name: "Klasyczna sesja Reiki",
          desc: "Praca z energią dla regeneracji, spokoju i rozładowania napięcia. Stacjonarnie lub zdalnie.",
          price: "od 000 ₴", cta: "Umów się",
        },
        {
          tag: "głębsza praca", glyph: "❋",
          name: "Sesja «Pytanie — Rozwiązanie»",
          desc: "Indywidualna sesja, na której wspólnie rozkładamy konkretną sprawę i znajdujemy rozwiązanie.",
          price: "od 000 ₴", cta: "Umów się", featured: true,
        },
        {
          tag: "ustawienie", glyph: "✶",
          name: "Ustawienie",
          desc: "Metoda, która pomaga dostrzec ukryte przyczyny sytuacji i przywrócić wewnętrzną równowagę.",
          price: "od 000 ₴", cta: "Umów się",
        },
      ],
    },
    courses: {
      kicker: "03 · kursy",
      title: "Autorskie kursy",
      sub: "Pogłębione programy do systematycznej pracy nad sobą we własnym tempie.",
      items: [
        {
          tag: "kurs", name: "Kobieca siła",
          desc: "Kurs o powrocie do siebie, odzyskaniu energii i wewnętrznego oparcia. Praktyki, medytacje i wsparcie.",
          price: "od 000 ₴", cta: "Dowiedz się więcej",
        },
        {
          tag: "kurs", name: "Scenariusz",
          desc: "Praca ze scenariuszem życiowym: dostrzec powtarzające się wzorce i przepisać je po swojemu.",
          price: "od 000 ₴", cta: "Dowiedz się więcej",
        },
      ],
    },
    mini: {
      kicker: "04 · miniprodukty",
      title: "Miniprodukty do samodzielnej pracy",
      sub: "Niewielkie praktyczne materiały — by zacząć pracę nad sobą już dziś.",
      priceLabel: "000 ₴",
      items: [
        { name: "Cele. Manifest. Pragnienia.", desc: "Jak stawiać cele, które się spełniają, i odzyskać prawo do pragnień." },
        { name: "Feng shui — podstawy dla początkujących", desc: "Proste zasady przestrzeni, która wspiera ciebie i twoją energię." },
        { name: "Przeznaczenie i Misja", desc: "Praktyka do odnalezienia własnego kierunku i sensu." },
        { name: "Cień i subosobowości", desc: "Poznanie swoich ciemnych części — bez lęku i oceny." },
        { name: "Bogactwo. Pieniądze. Realizacja.", desc: "Praca z przekonaniami o pieniądzach i przyzwoleniem na dobrobyt." },
      ],
    },
    meditations: {
      kicker: "05 · medytacje",
      title: "Pakiet medytacji",
      sub: "Autorskie medytacje, które przywracają kontakt z ciałem i spokojem. Słuchaj w dogodnym czasie, we własnym tempie.",
      features: ["medytacje w nagraniu", "dostęp po opłacie — na zawsze", "format online"],
      cta: "Uzyskać dostęp",
    },
    reviews: {
      kicker: "06 · opinie i historie",
      title: "Historie transformacji",
      sub: "Prawdziwe potrzeby i rezultaty klientek. Imiona — za zgodą.",
      requestLabel: "Potrzeba",
      resultLabel: "Rezultat",
      items: [
        {
          name: "Ołena", role: "33 lata",
          request: "Ciągły niepokój i poczucie, że żyje nie swoim życiem.",
          result: "Po miesiącu pracy wróciła jasność i spokój. Zdecydowała się na zmianę pracy.",
        },
        {
          name: "Iryna", role: "41 lat",
          request: "Zmęczenie, które nie mijało nawet po odpoczynku.",
          result: "Odzyskała energię, nauczyła się czuć swoje granice i mówić «nie».",
        },
        {
          name: "Maria", role: "29 lat",
          request: "Nie rozumiała swojego kierunku i przeznaczenia.",
          result: "Znalazła oparcie w sobie i wyraźniej zobaczyła, dokąd zmierzać.",
        },
      ],
      cta: "Więcej opinii",
    },
    faq: {
      kicker: "07 · pytania",
      title: "Najczęstsze pytania",
      items: [
        { q: "Jak przebiega sesja?", a: "Spotykamy się online lub stacjonarnie. Najpierw krótko omawiamy twoją potrzebę, potem — sama praktyka. Po sesji dzielę się spostrzeżeniami i wskazówkami." },
        { q: "Czy to jest bezpieczne?", a: "Tak. Reiki to łagodna metoda bez przeciwwskazań. Nie zastępuje pomocy medycznej, a uzupełnia troskę o siebie." },
        { q: "Ile trwa praca?", a: "Zależy od potrzeby. Czasem wystarcza jedna sesja, przy głębszych zmianach — seria spotkań lub kurs. Format dobieramy wspólnie." },
        { q: "Czym jest Reiki?", a: "To praktyka pracy z energią dla przywrócenia równowagi, spokoju i zasobów. Działa łagodnie — przez dotyk lub zdalnie." },
        { q: "Jak wybrać format?", a: "Najprościej — zacząć od bezpłatnej konsultacji. W 20–30 minut zrozumiem twoją potrzebę i podpowiem, co będzie dla ciebie odpowiednie." },
        { q: "Czy to jest sprzeczne z moją religią?", a: "Nie. Reiki to nie religia i nie wymaga wiary. To praktyka troski o siebie, która łączy się z każdym światopoglądem." },
      ],
    },
    contacts: {
      kicker: "08 · kontakt",
      title: "Zróbmy pierwszy krok",
      sub: "Napisz do mnie w dowolny dogodny sposób albo zostaw zgłoszenie — odpowiem osobiście.",
      channels: [
        { kind: "Instagram", value: "@nataliarudnik", href: "#" },
        { kind: "TikTok", value: "@nataliarudnik", href: "#" },
        { kind: "Telegram", value: "@nataliarudnik", href: "#" },
        { kind: "Email", value: "hello@nataliarudnik.com", href: "mailto:hello@nataliarudnik.com" },
        { kind: "WhatsApp", value: "+380 00 000 00 00", href: "#" },
      ],
      orWrite: "albo zostaw zgłoszenie:",
      formName: "twoje imię",
      formContact: "email lub telefon",
      formCta: "Wyślij zgłoszenie",
      footnote: "odpowiadam osobiście, zwykle w ciągu dnia",
    },
    footer: {
      tagline: "wracaj do siebie — głęboko i naprawdę",
      copyright: "© 2026 Natalia Rudnik",
      links: ["Polityka prywatności", "Regulamin"],
    },
  },
};
